
# configuration to enable the user creations inside the keycloak
keycloak:
    server-url: http://localhost:9999
    realm: ecommerce_realm
    client-secret: bK6I3SHJV3qgBsxv7wB3KyEamlcDwiO8
    client-id: spring-boot-app
file:
    client-path: /files
    storage-location: /Users/kk/Engineering/ite-images/
    base-url: http://localhost:${server.port}${file.client-path}/
# http://localhost:8080/files/
spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:9999/realms/ecommerce_realm

#      configuration for the client
#        client:
#          registration:
#            keycloak:
#              client-id: "spring-boot-app"
#              client-secret: "bK6I3SHJV3qgBsxv7wB3KyEamlcDwiO8"
#              scope: openid, profile, email, offline_access
#              authorization-grant-type: authorization_code
#              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#          provider:
#            keycloak:
#              # change your actual keycloak host port and realm name
#              issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
        # In order to verify the token being sent to client
    servlet:
      multipart:
        max-file-size: 10MB # max allocation for single file size
        max-request-size: 30MB # ... for the whole request
  #    security:
#      user:
#        name: developer
#        password: pass12345
    application:
      name: product-api-simple-demo
# jpa, postgres
    datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: create-drop    # create | update | none
      show-sql: true          # log generated SQL
      properties:
        hibernate:
          format_sql: true
server:
  port: 8080
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE