name: PR Validation pipeline
# condition
on:
#  push:
#    branches:
#      - 'feature/**'
#      - 'fix/**' # hotfix
  pull_request:
      branches:
        - main
jobs:
  build-and-analyze:
    name: Build, Tests, and Sonarqube Analysis
    runs-on: ubuntu-latest
    environment: SONARQUBE
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
                ${{ runner.os }}-gradle-

      - name: Cache Sonarqube packages
        uses: actions/cache@v4
        with:
            path: ~/.sonar/cache
            key: ${{runner.os}}-sonar
            restore-keys: ${{runner.os}}-sonar
      - name: Grant permission to run gradlew
        run: chmod +x ./gradlew
      - name: Create .env from SECRET
        env:
            ENV_CONTENT: ${{secrets.ENV_FILE}}
        run: |
            echo "$ENV_CONTENT" > .env
      - name: Build and Run Sonar
        env:
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
            SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
        run:
            ./gradlew build sonar -Dsonar.qualitygate.wait=true --info
      - name: Sonar Summary
        if: always() # Runs even if the previous step fails
        run: |
          echo "## SonarQube Analysis" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Project:** ecommerce-spring-api" >> $GITHUB_STEP_SUMMARY
          echo "- **Dashboard:** https://ite-sonarqube.anajak-khmer.site/dashboard?id=ecommerce-spring-api" >> $GITHUB_STEP_SUMMARY
          
          # Check if the sonar step succeeded or failed
          if [ "${{ steps.sonar.outcome }}" == "success" ]; then
            echo "- **Status:** :white_check_mark: **PASSED**" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Status:** :x: **FAILED**" >> $GITHUB_STEP_SUMMARY
          fi