name: Release Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Build, Publish Docker Image
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow pull only pull the latest version

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache SonarQube Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Create .env
        env:
          ENV_CONTENT: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_CONTENT" > .env

      - name: Build & Test
        run: |
          ./gradlew clean build

      # Optional
      - name: SonarQube Analysis
        if: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradlew sonar

      - name: Using COMMIT SHA as tag
        run: |
            echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Login with dockerhub
        run:
            echo "${secrets.DH_PASSWORD}" | docker login -u ${secrets.DH_USERNAME} --password-stdin
      - name: Build the docker image
        run: |
            docker build -t ${{secrets.USERNAME}}/ite-spring-g3/v1.0.${{env.TAG}} .
      - name: Store the image inside the registry
        run: |
            docker push ${{secrets.USERNAME}}/ite-spring-g3/v1.0.${{env.TAG}}
      - name: logout
        if: always()
        run: docker logout
  deploy:
      needs: release
      runs-on: ubuntu-latest
      environment: PRODUCTION

      steps:
        - name: COPY prod-compose.yaml to the server
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.GCP_IP }}
            username: ${{ secrets.GCP_USER }}
            key: ${{ secrets.GCP_PRIVATE_KEY}}
            source: "prod-compose.yaml"
            target: "/opt/product-api"
        - name: Deploy on GCP
          uses: appleboy/ssh-action@v1.0.0
          env:
            IMAGE: ${{secrets.USERNAME}}/ite-spring-g3/v1.0.${{env.TAG}}
          with:
              host: ${{ secrets.GCP_IP }}
              username: ${{ secrets.GCP_USER }}
              key: ${{ secrets.GCP_PRIVATE_KEY}}
              envs: IMAGE
              script: |
                cd /opt/product-api
                echo "Deploying Image : $IMAGE" 
                
                echo "Update the image name and tags" 
                yq -i '.services."product-api".image = strenv(IMAGE)' prod-compose.yaml
                
                docker login -u ${{secrets.DH_USERNAME}} -p ${{secrets.DH_PASSWORD}}
                docker compose up -d 
                docker image prune -f 
            
            
